apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: dali-storage-class
provisioner: kubernetes.io/azure-file
parameters:
  skuName: {{ .Values.dali.sku | default "Premium_ZRS" }}      # Random access common, a disaster if it disappears.
reclaimPolicy: Retain
allowVolumeExpansion: true
