# Persistent Volume Claim for main data
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ printf "%s-datastorage-pv-claim" (include "hpcc.fullname" .) }}
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "hpcc.chart" . }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.data.storageSize }}
  storageClassName: "data-storage-class"
