# Persistent Volume Claim for generated dlls
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ printf "%s-dllserver-pv-claim" (include "hpcc.fullname" .) }}
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "hpcc.chart" . }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.dlls.storageSize }}
  storageClassName: "dll-storage-class"
