name: Check for change in helm output

on:
  push:
    branches:
      - "master"
      - "candidate-*"
      - "!candidate-7.8.*"
      - "!candidate-7.6.*"
      - "!candidate-7.4.*"
      - "!candidate-7.2.*"
      - "!candidate-7.0.*"
      - "!candidate-6.*"
  pull_request:
    branches:
      - "master"
      - "candidate-*"
      - "!candidate-7.8.*"
      - "!candidate-7.6.*"
      - "!candidate-7.4.*"
      - "!candidate-7.2.*"
      - "!candidate-7.0.*"
      - "!candidate-6.*"

jobs:
  pre_job:
     # continue-on-error: true # Uncomment once integration is finished
     runs-on: ubuntu-20.04
     # Map a step output to a job output
     outputs:
       helm: ${{ steps.skip_check.outputs.helm }}
     steps:
       - id: skip_check
         uses: hpcc-systems/github-actions/changed-modules@main
         with:
           github_token: ${{ github.token }}
  build:
    name: "Check helm chart lint"
    runs-on: ubuntu-20.04
    needs: pre_job
    #if: ${{ github.repository == 'hpcc-systems/HPCC-Platform' && needs.pre_job.outputs.helm }}
    if: ${{ needs.pre_job.outputs.helm }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: false
      - uses: azure/setup-helm@v3
        with:
          version: 'latest'
          token: ${{ secrets.GITHUB_TOKEN }}
        id: install
      - name: Test
        working-directory: .
        run: |
          helm template helm/hpcc > ${{ runner.temp }}/newoutput.txt
          git fetch --no-tags --prune --progress --no-recurse-submodules --depth=1 origin ${{ github.base_ref }}
          git checkout ${{ github.base_ref }}
          helm template helm/hpcc > ${{ runner.temp }}/oldoutput.txt
          diff ${{ runner.temp }}/oldoutput.txt ${{ runner.temp }}/newoutput.txt
